# Platform Configuration

# Infrastructure Settings
infrastructure:
  providers:
    - name: aws
      region: us-east-1
      credentials_file: ~/.aws/credentials
    - name: kubernetes
      config_file: ~/.kube/config
    - name: docker
      socket: unix:///var/run/docker.sock

# Deployment Settings
deployment:
  environments:
    - name: development
      infrastructure: kubernetes
      namespace: dev
    - name: staging
      infrastructure: kubernetes
      namespace: staging
    - name: production
      infrastructure: kubernetes
      namespace: prod

# Monitoring Settings
monitoring:
  prometheus:
    endpoint: http://prometheus:9090
  grafana:
    endpoint: http://grafana:3000
    api_key: ${GRAFANA_API_KEY}

# Security Settings
security:
  scan_schedule: "0 0 * * *"  # Daily at midnight
  vulnerability_database: ./data/vuln_db.json
  alerting:
    email: devops-alerts@company.com
    slack_webhook: ${SLACK_WEBHOOK_URL}

# Logging Settings
logging:
  level: INFO
  file: ./logs/platform.log
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# API Settings
api:
  host: 0.0.0.0
  port: 5000
  debug: false
  secret_key: ${API_SECRET_KEY}

# Web Interface Settings
web_interface:
  theme: dark
  refresh_interval: 30  # seconds
  features:
    - infrastructure_management
    - deployment_pipelines
    - monitoring_dashboard
    - security_reports
